app:
  build: .
  container_name: file-storage.app
  #image: microsoft/aspnet:1.0.0-rc1-update1  
  ports:
   - "8082:5000"
  expose:
    - "5000"
app-dev:
  #build: .
  container_name: file-storage.app-dev
  image: microsoft/aspnet:1.0.0-rc1-update1
  volumes:
   - .:/src
  ports:
   - "8082:5000"
  expose:
    - "5000"