# contains dotnet CLI and only coreclr
FROM microsoft/dotnet:latest

RUN sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'

RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

RUN apt-get -y --force-yes update 

RUN apt-get -y --force-yes install dotnet=1.0.0.001331-1


#EXPOSE 5000/tcp
ENTRYPOINT ["/bin/bash"]
