# contains dotnet CLI and only coreclr
FROM microsoft/dotnet:latest

RUN echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list

RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

RUN apt-get -y --force-yes update 

# RUN apt-get -y --force-yes install dotnet=1.0.0.001331-1
# cause 1.0.16779 was instaleld and new policy of microsoft starts with 1.0.0 
# again. So dongrade to latest starting with 1.0.0
RUN apt-get -y --force-yes install dotnet=1.0.0*

#EXPOSE 5000/tcp
#ENTRYPOINT ["/bin/bash"]
